name: 'CI/CD'
on:
  workflow_dispatch: { }

  pull_request:
    branches: [ 'main' ]

  push:
    branches: [ 'main' ]

jobs:
  config:
    runs-on: 'ubuntu-24.04'
    permissions: { }
    outputs:
      linux-runner-image: ${{ steps.constants.outputs.linux-runner-image }}
      linux-compiler: ${{ steps.constants.outputs.linux-compiler }}
    steps:
      - name: 'Define constants'
        id: 'constants'
        run: |
          echo "linux-runner-image=ubuntu-24.04" >> $GITHUB_OUTPUT
          echo "linux-compiler=llvm-21" >> $GITHUB_OUTPUT

  lint-commits:
    runs-on: ${{ needs.config.outputs.linux-runner-image }}
    permissions:
      contents: 'read'
    needs: [ 'config' ]
    steps:
      - name: 'Clone the repository'
        uses: 'actions/checkout@v6'
        with:
          fetch-depth: 0

      - name: 'Setup node'
        uses: 'actions/setup-node@v6'
        with:
          node-version: lts/*

      - name: 'Install commitlint'
        run: npm install -D @commitlint/cli @commitlint/config-conventional

      - name: 'Validate commits'
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            npx commitlint --from ${{ github.event.before }} --to ${{ github.event.after }} --verbose
          else
            npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
          fi